before_install:
  - brew update > /dev/null; if brew outdated | grep -qx xctool; then brew upgrade xctool; fi  # Ensure that xctool is up-to-date
language: objective-c
xcode_workspace: Soundie.xcworkspace
xcode_project: Soundie.xcodeproj
xcode_scheme: Soundie Ad-Hoc
xcode_sdk: iphonesimulator8.0
osx_image: xcode61